; ini file giving numbers of options in each
; stock comment category.

[stock_warn]
num_entries=12

[stock_attack]
num_entries=12

[stock_flee_gangster]
num_entries=3

[stock_flee_civillian]
num_entries=4

[stock_surrender_cargo]
num_entries=6

[stock_surrender_no_cargo]
num_entries=4

[stock_complain]
num_entries=7

[stock_distress]
num_entries=4

[stock_thanks]
num_entries=5

;
; NOTE
;
; Keep the _ at the end of each station section key in.  They mean one less 
; string concatenation in the script
;

[stock_station_greet_neutral_]
num_entries=5

[stock_station_greet_friendly_]
num_entries=4

[stock_station_warning_gentle_]
num_entries=2

[stock_station_warning_gentle_cops_]
num_entries=3

[stock_station_warning_severe_]
num_entries=2

[stock_station_warning_restricted_]
num_entries=1

[stock_station_attack_guarded_]
num_entries=2

[stock_station_attack_guarded_cops_]
num_entries=2

[stock_station_attack_severe_]
num_entries=5

[stock_station_destroyed_]
num_entries=2




