;
; (c) 1999 Particle Systems Ltd. All Rights Reserved
;
; player_base.ini
;
; INI file for the player base.
;
; Revision control information:
;
; $Header: /iwar2/resource/sims/Multiplayer/MineSwitch.INI 2     9/08/01 11:43 Carl $
;

[Class]
name=icCargoPod


[SetupScene]
name=lws:/sims/multiplayer/MineSwitch
null=root

[Avatar]
name=lws:/avatars/PowerUps/MineSwitch_Setup

[CollisionHull]
name=collision_hull:/collisionhulls/MineSwitch_Hull

[Subsims]
template[0]=ini:/subsims/dockports/universal_port
null[0]=switchdock

[Properties]

; The name of the object
name="Mine Activator"

type="T_CargoPod"

; Sim radius in metres
radius=300

;docking port priority
docking_priority=11

width=100
height=100
length=200

; ** Damage model properties
hit_points=50

; Brightness for the sensors to spot
brightness=1.0
min_brightness=1.0
