; (c) 1999 Particle Systems Ltd. All Rights Reserved
;
; old_cruiser.ini
;
; Template for the old (iwar 1) navy  cruiser
;
; Revision control information:
;
; $Header: /iwar2/resource/sims/Multiplayer/old_cruiser.ini 1     18/07/01 14:57 Carl $
;

[Class]
name=icShip

[Avatar]
name=lws:/avatars/cruiser/setup

[CollisionHull]
name=collision_hull:/collisionhulls/cruiser_hull

[SetupScene]
name=lws:/sims/multiplayer/old_cruiser

[Subsims]

; Dockports
template[0]=ini:/subsims/dockports/universal_port
null[0]=dockport
template[1]=ini:/subsims/dockports/universal_port
null[1]=dockport01
template[2]=ini:/subsims/dockports/universal_port
null[2]=dockport02

; Systems
template[3]=ini:/subsims/systems/nonplayer/nps_sensor
template[4]=ini:/subsims/systems/nonplayer/nps_lds
template[5]=ini:/subsims/systems/nonplayer/nps_capsule_drive
template[6]=ini:/subsims/systems/nonplayer/nps_autorepair_capital
template[7]=ini:/subsims/systems/nonplayer/nps_crew
null[7]=crew

; Weapons (probably too many at the moment)
template[8]=ini:/subsims/systems/nonplayer/nps_heavy_pbc
null[8]=left_main_gun

template[9]=ini:/subsims/systems/nonplayer/nps_heavy_pbc
null[9]=right_main_gun

template[10]=ini:/subsims/systems/nonplayer/nps_turret_cannon_wide
null[10]=mid_gun

template[11]=ini:/subsims/systems/nonplayer/nps_turret_cannon_wide
null[11]=lower_gun

template[12]=ini:/subsims/systems/nonplayer/nps_turret_assault_cannon
null[12]=rear_gun1

template[13]=ini:/subsims/systems/nonplayer/nps_turret_assault_cannon
null[13]=rear_gun2

; LDAs
template[14]=ini:/subsims/systems/nonplayer/nps_lda_hard
null[14]=shield_1

template[15]=ini:/subsims/systems/nonplayer/nps_lda_hard
null[15]=shield_2

template[16]=ini:/subsims/systems/nonplayer/nps_lda_hard
null[16]=shield_3


[Properties]

; The name of the object
name=ship_type_navy_cruiser

; The threat rating 'points value' of the hull
threat= 300

; Damage model properties
hit_points=13500
armour=75

; Docking port priority
docking_priority=150

; Sim type (ship class)
type=T_Cruiser

; Dimensions
width=510
height=260
length=950

; Maximum linear speeds as a vector (m/s)
speed=(100,100,1000)

; Maximum linear acceleration as a vector (m/s/s)
acceleration=(15, 15, 40)

; Maximum angular rotation (deg/s)
yaw_rate=7
roll_rate=8
pitch_rate=7

; Maximum angular acceleration (deg/s/s)
yaw_accel=3
roll_accel=3
pitch_accel=3

; Applied in free flight to the max angular speed
angular_speed_boost=1.0

; Brightness for the sensors to spot
brightness=0.9
min_brightness=0.7
