;
; (c) 1999 Particle Systems Ltd. All Rights Reserved
;
; player_base.ini
;
; INI file for the player base.
;
; Revision control information:
;
; $Header: /iwar2/resource/sims/Multiplayer/PiracyBase03.INI 1     7/08/01 15:50 Carl $
;

[Class]
name=icStation

[SetupScene]
name=lws:/sims/multiplayer/PiracyBase03
null=root

[Avatar]
name=lws:/avatars/MODULARSTATIONS/Piracy03_Setup

[CollisionHull]
name=collision_hull:/collisionhulls/Piracy03_Hull

[Subsims]
;template[0]=ini:/subsims/dockports/universal_port
;null[0]=dock_arm_dock01
;template[1]=ini:/subsims/dockports/universal_port
;null[1]=dock_arm_dock02

[Properties]

; The name of the object
name="Refinery"

; Sim radius in metres
radius=300

; Sim mass in kilogrammes
;mass=40000000000

; The docking priority
docking_priority=1000

width=60
height=237
length=300

; ** Damage model properties
hit_points=9000000000
