;
; (c) 1999 Particle Systems Ltd. All Rights Reserved
;
; escape_tug.ini
;
; Template for the tug in which the player escapes from prison.
;
; Revision control information:
;
; $Header: /iwar2/resource/sims/ships/player/escape_tug.ini 26    6/07/01 14:18 James $
;

[Class]
name=icShip

[Avatar]
name=lws:/avatars/tug_hull/setup_escape

[CollisionHull]
name=collision_hull:/collisionhulls/tug2_hull

[SetupScene]
;name=lws:/sims/ships/player/escape_tug
name=lws:/sims/ships/common_setups/tug

[Subsims]

; Dockports
template[0]=ini:/subsims/dockports/universal_port
null[0]=dockport_rear

; Systems
template[1]=ini:/subsims/systems/player/powerplant_tug
template[2]=ini:/subsims/systems/player/accumulators
template[3]=ini:/subsims/systems/player/heatsink1
template[4]=ini:/subsims/systems/player/passive1_sensors
template[5]=ini:/subsims/systems/player/lds_class1
null[5]=lds
template[6]=ini:/subsims/systems/player/autorepair1
template[7]=ini:/subsims/systems/player/manoeuvre_thrusters
template[8]=ini:/subsims/systems/player/ships_drive
null[8]=drive
template[9]=ini:/subsims/systems/player/pbc
null[9]=nps_pbc
template[10]=ini:/subsims/systems/player/harrower_missile_magazine
null[10]=nps_missile_launcher
template[11]=ini:/subsims/systems/player/gnat_rocket_pod
null[11]=nps_missile_launcher
template[12]=ini:/subsims/systems/player/lda_defence
null[12]=shield_upper
template[13]=ini:/subsims/systems/player/life_support
null[13]=nps_crew

template[14]=ini:/subsims/systems/player/flare_magazine
null[14]=countermeasure

template[15]=ini:/subsims/systems/player/cpu1
 
template[16]=ini:/subsims/systems/player/lda_defence
null[16]=shield_lower

template[17]=ini:/subsims/systems/player/pbc
null[17]=nps_pbc


[Properties]

; The name of the object
name=ship_type_tug

; The threat rating 'points value' of the hull
threat=80

; Damage model properties
hit_points=1200
armour=65

; Sim type (ship class)
type="T_Tug"

; Docking port priority
docking_priority=85

; Dimensions
width=80
height=70
length=120

; Maximum linear speeds as a vector (m/s)
speed=(200,200,750)

; Maximum linear acceleration as a vector (m/s/s)
acceleration=(100, 100, 150)

; Maximum angular rotation (deg/s)
yaw_rate=60
roll_rate=60
pitch_rate=60

; Maximum angular acceleration (deg/s/s)
yaw_accel=30
roll_accel=30
pitch_accel=30

; Applied in free flight to the max angular speed
angular_speed_boost=1.3

; Brightness for the sensors to spot
brightness=0.6
min_brightness=0.4
