;
; (c) 1999 Particle Systems Ltd. All Rights Reserved
;
; sensor_disruptor.ini
;
; Template for a sensor disruptor mount point.
;
; Revision control information:
;
; $Header:
;

[Class]
name=icMountPoint

[Properties]
name=mountpoint_sensor_disruptor

; The type of this mountpoint - meaningful to the icMountPoint class
type=16384