;
; Simple deathmatch package
;

[Default]
; Name of the pog package 
PackageName = "iBombTag"

; Map to load


; Geography ini file
Geography = "generic_02"

; Human readable name
Name = "Bomb Tag"


; Default gameplay settings
ScoreLimit = 5
TimeLimit = 15

[BotShipTypes]

ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/storm_petrel"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"


[BotNamesA]

name[] = "Colonel Flustered"
name[] = "Beast of Bodmin"
name[] = "Kamakazi King"
name[] = "Fang the Unstable"
name[] = "The Spondon Flyer"
name[] = "Mad Dog"
name[] = "Yin Shi Nan Nu"
name[] = "Mayor of Simpleton"
name[] = "Plan 9"

[BotNamesB]

name[] = "Spanky"
name[] = "Ravanger"
name[] = "Muppet"
name[] = "Carlos Fandango"
name[] = "Bretski"
name[] = "Man of Bronze"
name[] = "BuhBuh"
name[] = "Tappinator"
name[] = "Jucy Moose"