;
; Simple deathmatch package
;

[Default]
; Name of the pog package 
PackageName = "ideathmatch"

; Map to load


; Geography INI file
Geography = "generic_02"

; Human readable name
Name = "Death Match"

; Default gameplay settings
ScoreLimit = 10
TimeLimit  = 15

[BotShipTypes]

ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"


[BotNamesA]

name[] = "Colonel Flustered"
name[] = "Bad Boris"
name[] = "Kamakazi King"
name[] = "Fang the Unstable"
name[] = "Killer Insect"
name[] = "Mad Dog"
name[] = "Yin Shi Nan Nu"
name[] = "Mayor of Simpleton"
name[] = "Plan 9"

[BotNamesB]

name[] = "Spanky"
name[] = "Ravanger"
name[] = "Muppet"
name[] = "Carlos Fandango"
name[] = "Bretski"
name[] = "Man of Bronze"
name[] = "BuhBuh"
name[] = "Tappinator"
name[] = "Jucy Moose"