;
; team deathmatch package
;

[Default]
; Name of the pog package 
PackageName = "iIndiesVsCorporates"

; Map to load


; Geography INI file
Geography = "piracy"


; Human readable name
Name = "Indies versus Corporates"

; Default gameplay settings
TimeLimit  = 15

; game type specific properties
[Piracy]
; cargo value defended is worth n times more than cargo pirated
; due to increased difficulty in defending rather than pirating.
CargoSavedMultiplier = 2.0


[BotShipTypes]

ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"
ship[] = "ini:/sims/ships/multiplayer/heavy_corvette"
ship[] = "ini:/sims/ships/multiplayer/fast_attack"


[BotNamesA]

name[] = "Colonel Flustered"
name[] = "Bad Boris"
name[] = "Kamakazi King"
name[] = "Fang the Unstable"
name[] = "Killer Insect"
name[] = "Mad Dog"
name[] = "Yin Shi Nan Nu"
name[] = "Mayor of Simpleton"
name[] = "Plan 9"

[BotNamesB]

name[] = "Spanky"
name[] = "Ravanger"
name[] = "Muppet"
name[] = "Carlos Fandango"
name[] = "Bretski"
name[] = "Man of Bronze"
name[] = "BuhBuh"
name[] = "Tappinator"
name[] = "Jucy Moose""