;;
; (c) 1999 Particle Systems Ltd. All Rights Reserved
;
; clusters.ini
;
; Cluster information for Independence War II
;
; Revision control information:
;
; $Header: /iwar2/resource/geog/multiplayer_clusters.ini 12    8/08/01 10:31 Carl $
;

[badlands]

system[] = map:/geog/multiplayer/carls_world
system[] = map:/geog/multiplayer/buhbuhworld
system[] = map:/geog/multiplayer/green_dm
system[] = map:/geog/multiplayer/blue_dm
system[] = map:/geog/multiplayer/firey_dm
system[] = map:/geog/multiplayer/mine_dm
;system[] = map:/geog/badlands/dante
;system[] = map:/geog/badlands/firefrost

;system[] = map:/geog/badlands/hoffers_wake
;system[] = map:/geog/badlands/mwari
;system[] = map:/geog/badlands/santa_romera
;system[] = map:/geog/badlands/coyote
;system[] = map:/geog/badlands/kompira
;system[] = map:/geog/badlands/eureka
;system[] = map:/geog/badlands/dagda


;[gagarin]

;system[] = map:/geog/gagarin/new_bavaria
;system[] = map:/geog/gagarin/drake
;system[] = map:/geog/gagarin/ishime
;system[] = map:/geog/gagarin/owens_star
;system[] = map:/geog/gagarin/osprey
;system[] = map:/geog/gagarin/formhault
;system[] = map:/geog/gagarin/batatas

