;
; (c) 1999 Particle Systems Ltd. All Rights Reserved
;
; remote_missile.ini
;
; Template for a remote missile
;
; Revision control information:
;
; $Header: /iwar2/resource/sims/weapons/remote_missile.ini 8     6/08/01 11:54 Carl $
;

[Class]
name=icRemoteMissile

[Avatar]
name=lws:/avatars/remote/setup

[Subsims]

[Properties]

; The name of the object
name="Remote Missile"

;the pod it fits in
pod_template=ini:/subsims/cargopods/remote_pod

; Sim type (ship class)
type="T_Missile"

; threat rating
threat=40

; ** Damage model properties
hit_points=100
armour=20

; Sim radius in metres
radius=3

; Missile properties
lifetime=60
penetration=60
damage=1600
blast_radius=2000

; has an area of effect of about 2.5 km radius

; remote pilotable
remote=1

; ** Flight model properties

width=1.6
height=1.6
length=12.6

;Maximum linear speeds as a vector (m/s)
speed=(100,100,2200)

;Maximum linear acceleration as a vector (m/s/s)
acceleration=(150, 150, 280)

;NOTE: The angular values will be critical in that certain ships
;will be able to out-turn missiles and avoid the intercept
; - tweak as necessary

;Maximum angular rotation (deg/s)
yaw_rate=120
roll_rate=180
pitch_rate=120

;Maximum angular acceleration (deg/s/s)
yaw_accel=120
roll_accel=180
pitch_accel=120

; Applied in free flight to the max angular speed
angular_speed_boost=1.4
