[Planets]

atmosphere_height = 1.1

rocky_planet_textures[] = "texture:/images/planets/Terrain1"
rocky_planet_textures[] = "texture:/images/planets/Terrain2"
rocky_planet_textures[] = "texture:/images/planets/Terrain3"
rocky_planet_textures[] = "texture:/images/planets/Terrain4"
rocky_planet_textures[] = "texture:/images/planets/LandWater1"
rocky_planet_textures[] = "texture:/images/planets/LandWater2"
rocky_planet_textures[] = "texture:/images/planets/LandWater4"
rocky_planet_textures[] = "texture:/images/planets/Cracks"

gassy_planet_textures[] = "texture:/images/planets/Stripes1"
gassy_planet_textures[] = "texture:/images/planets/Stripes2"
gassy_planet_textures[] = "texture:/images/planets/Stripes3"
gassy_planet_textures[] = "texture:/images/planets/Stripes4"
gassy_planet_textures[] = "texture:/images/planets/Stripes5"
gassy_planet_textures[] = "texture:/images/planets/Stripes6"
gassy_planet_textures[] = "texture:/images/planets/gas1"
gassy_planet_textures[] = "texture:/images/planets/gas2"
gassy_planet_textures[] = "texture:/images/planets/gas3"
gassy_planet_textures[] = "texture:/images/planets/gas4"

;m_detail_planet_textures[] =

atmosphere_planet_textures[] = "texture:/images/planets/clouds1"
atmosphere_planet_textures[] = "texture:/images/planets/clouds2"
atmosphere_planet_textures[] = "texture:/images/planets/clouds3"
atmosphere_planet_textures[] = "texture:/images/planets/clouds4"

atmosphere_bump_textures[] = "texture:/images/planets/clouds1_bump"
atmosphere_bump_textures[] = "texture:/images/planets/clouds2_bump"
atmosphere_bump_textures[] = "texture:/images/planets/clouds3_bump"
atmosphere_bump_textures[] = "texture:/images/planets/clouds4_bump"

planet_models[] = "model:/avatars/planets/Planet_LOD2"
planet_models[] = "model:/avatars/planets/Planet_LOD1"
planet_models[] = "model:/avatars/planets/Planet_LOD0"

detail_switch[] = 0.03
detail_switch[] = 0.2
detail_switch[] = 0.9

max_rings = 8
rings_prob = 1.0

//
// Atmospheric pressure below this value will not
// produce at atmosphere
//
atmosphere_threshold = 0.1

;
; Colours for when colours can't be worked out
;

; Rocks
colours[] = (168, 168, 116)
colours[] = (120, 145, 14)
colours[] = (64,  13,  7)

; Dark Rocks
;;colours[] = (64,  13,  7)
colours[] = (99,  46,  40)
colours[] = (48,  48,  23)

; Land
colours[] = (191, 169, 128)
colours[] = (250, 224, 168)
colours[] = (107, 97,  82)

; Water
colours[] = (65, 81,  112)
colours[] = (46, 46,  46)

