;
; Copyright (c) 1999-2001 Particle Systems Ltd.
;
; defaults.ini
;
; Flux default system configuration file for IW2:EOC. This file is used
; by the 'restore defaults' option in the front end.
;
; Revision control information:
;
; $Header: /iwar2/flux.ini 55    6/08/01 12:22 Carl $
;

;
; Class static properties
;

[FcApp]
class_name = iwar2.icGame
display_name = IW2:EOC
short_name = iwar2
allow_multiple_instances = 0

[FcClient]
taunts[0] = "Nice shot"
taunts[1] = "Eat lead, suckers"
taunts[2] = "You will live to regret that"
taunts[3] = "Go chew on an antineutrino"
password =

[FcConsole]
font_url = font:/fonts/ocrb_8pt
scrollback_lines = 400

[FcDetailSwitchNode]
global_detail_scale = 0.4
cull_detail = 0.00375
box_detail = 0.01575

[FcGame]
graphics_device = dx7graph.fcGraphicsDeviceD3D
sound_device = dx7sound.fcSoundDeviceDA
network_device = dx8net.fcNetworkDeviceDP8
input_device = dxinput.fcInputDeviceDI
cdaudio_device = 
movie_device = binkmovie.fcMovieDeviceBink
cd_key = 
disable_sound = 0
full_screen = 1
width = 800
height = 600
bit_depth = 32
video_driver = 

[fcGraphicsDeviceD3D]
use_compressed_textures = 1
texture_quality = 1
texture_size = 1
z_depth = 0
use_hardware_tnl = 1
vsync = 1
max_simultaneous_lights = 4
use_multitexture = 1
override_pixel_texel_offsets = 0
pixel_offset_x = -0.5
pixel_offset_y = -0.5
texel_offset_x = 0
texel_offset_y = 0
attenuation = 0
use_static_buffers = 0
use_trilinear = 0
use_mipmaps = 1
use_alpha_test = 1
use_w_buffer = 1
use_fog = 1
use_anisotropic_filtering = 0
use_modulate_2x = 1
brightness = 0.5
video_memory_size = 0

[fcInputDeviceDI]
file = ./resource/forcefeedback/*.ffe
dead_zone_x = 0.175
dead_zone_y = 0.175
dead_zone_z = 0.175
dead_zone_rx = 0.175
dead_zone_ry = 0.175
dead_zone_rz = 0.175
use_force_feedback = 1

[FcInputMapper]
repeat_period = 0.08
initial_delay = 0.5
input_scheme_ini = configs/default.ini

[FcModel]
optimise_on_load = 1
shader_quality = 2
generate_texture_basis = 0

[fcMovieDeviceBink]
volume = 1
no_thread_io = 0
native_size = 0
readahead_buffer_size = 0

[FcResourceManager]
search_paths[0] = .\resource
search_paths[1] = .\streams
search_cd = 1
generate_access_log = 0

[FcSceneDemoScreen]
no_logos = 0
no_stats = 0
pan_per_mickey = 0.9
tilt_per_mickey = 0.9
roll_per_mickey = 0.1
zoom_per_mickey = 7.5
input_acceleration = 20.7
backdrop = 
back_ini = 

[FcScriptEngine]
overall_timeslice = 3
task_timeslice = 3

[FcServer]
cycle_packages[0] = dm
cycle_packages[1] = tdm
cycle_maps[0] = ini:/multiplayer/maps/generic_02
cycle_maps[1] = ini:/multiplayer/maps/generic
ai_bots = 1
ai_bots_skill = 0.6
arcade_mode = 0
ai_bots_count = 0
query_port = 26900
query_location = UK
password =
internet_visible = 1

[fcNetworkDeviceDP8]
dplay_port = 2313


[FcServerBrowser]
session_enum_timeout = 100

[fcSoundDeviceDA]
distance_factor = 0.5
rolloff_factor = 0.27
doppler_shift_factor = 0.05
effects_volume = 0.8
speech_volume = 0.7
music_volume = 0.5

[FiInputDevice]
feedback_strength = 0

[FiMovieDevice]
volume = 1

[icAggressorShield]
penetration_armour_factor = 0.7
max_damage_factor = 5
min_damage_factor = 0.25

[icArcadeCamera]
speed = 3.8
range = 4
field_of_view = 1.2

[icBeamProjector]
heat_scale = 5

[icBullet]
mass_scale = 0.001

[icCannon]
heat_scale = 5

[icCapsuleEntryBlankAvatar]
sound_url = ini:/audio/sfx/capsule_entry
sound_tunnel_url = ini:/audio/sfx/capsule_tunnel
feedback_url = ini:/forcefeedback/capsule_entry
flash_time = 0.5

[icCapsuleSpace]
min_exit_speed = 500
max_exit_speed = 2000

[icChaseCamera]
speed = 1
initial_range = 4
min_range = 2
max_range = 10
field_of_view = 1.2

[icClient]
render_world = 1
render_headup = 1
render_director = 1
preload_sims[0] = ini:/sims/ships/utility/freighter
preload_sims[1] = ini:/sims/ships/utility/freightpod
preload_sims[2] = ini:/sims/ships/utility/containercarrier
preload_sims[3] = ini:/sims/ships/utility/containerpod
preload_sims[4] = ini:/sims/ships/utility/cargo_pod
preload_sims[5] = ini:/sims/ships/utility/fueltransporter_long
preload_sims[6] = ini:/sims/ships/utility/megatransporter
preload_sims[7] = ini:/sims/ships/utility/megapod
preload_sims[8] = ini:/sims/ships/utility/tug
preload_sims[9] = ini:/sims/ships/utility/puffin
preload_sims[10] = ini:/sims/ships/utility/truck
preload_sims[11] = ini:/sims/ships/utility/flitter
preload_sims[12] = ini:/sims/ships/navy/old_corvette
preload_sims[13] = ini:/sims/ships/navy/fighter
preload_sims[14] = ini:/sims/ships/cops/fighter
preload_sims[15] = ini:/sims/ships/cops/interceptor
preload_sims[16] = ini:/sims/ships/independent/cutter
preload_sims[17] = ini:/sims/ships/utility/snrv

[icCluster]
lp_queueing_distance_equiv = 2e+010

[icConversationCamera]
field_of_view = 1.1
rotation_rate = 0.08

[icDirector]
pan_per_mickey = 0.2
tilt_per_mickey = 0.2
roll_per_mickey = 0.15
zoom_per_mickey = 10
input_acceleration = 3.7
letterbox_transition_time = 1
min_cut_time = 1
feedback_scale = 1
feedback_url = ini:/forcefeedback/shake

[icDollyCamera]
speed = 1
initial_range = 4
min_range = 2
max_range = 10
field_of_view = 1.2

[icDropCamera]
min_time = 1.5
max_time = 3
field_of_view = 1.1

[icExternalCamera]
pan_rate = 3.8
tilt_rate = 3.8
roll_rate = 3.65
zoom_rate = 2.3
min_zoom = 1
max_zoom = 150
initial_zoom = 3
field_of_view = 1.25

[icFactions]
hate_dislike = -0.6
dislike_neutral = -0.2
neutral_like = 0.2
like_love = 0.6

[icGame]
multiplayer_only = 0
movies[0] = /movies/infogrames
movies[1] = /movies/psys
movies[2] = /movies/intro
comsec_discovery = 0
base_discovery = 0
base_entry = 0
jail_break = 0
outro = 0

[icGUIMovie]
az = 0
ocal = 0
ycal = 1
jaffs = 0
lori = 0
smith = 0

[icHUD]
use_thick_lines = 1
flash_delay = 6
flash_frequency = 3
elements[0] = icHUDReferenceGrid
elements[1] = icHUDLagrangeIcon
elements[2] = icHUDWaypointIcon
elements[3] = icHUDBrackets
elements[4] = icHUDContrails
elements[5] = icHUDTargetMFD
elements[6] = icHUDWeapons
elements[7] = icHUDOrbRadar
elements[8] = icHUDShields
elements[9] = icHUDClock
elements[10] = icHUDContactList
elements[11] = icHUDReticle
elements[12] = icHUDMenuReticle
elements[13] = icHUDDebug
elements[14] = icHUDMessage
elements[15] = icHUDShipStatus
elements[16] = icHUDEditBoxElement
elements[17] = icHUDStarmap
elements[18] = icHUDEngineering
elements[19] = icHUDLog
elements[20] = icHUDObjectives
elements[21] = icHUDScore
menu_timeout = 30

[icHUDMessage]
message_delay = 5
prompt_delay = 10
new_message_flash_frequency = 0.333333
caution_flash_frequency = 1

[icHUDOrbRadar]
use_thick_stalks = 1

[icInternalCamera]
neck_stiffness = 2
acceleration_stiffness = 1
acceleration_scale = 0.01
yaw_ratio = 0.25
pitch_ratio = 0.4
roll_ratio = 0.25
lateral_ratio = (-0.15,-0.2,-0.2)
focal_length = 100
field_of_view = 1.1

[icLDSDrive]
fraction_of_difference_gained_per_sec_squared = 0.025
max_fraction_of_difference_gained_per_sec = 0.8

[icMagazine]
rocket_launch_likelihood_per_ammo_fraction = 0.1
squared_radius_firing_tolerance = 15

[icMissileMagazine]
missile_boat_launch_likelihood = 0.01
missile_launch_likelihood_per_ammo_fraction = 0.005

[icPlanetAvatar]
3rfts_mode = 0

[icPlayerLDA]
min_energy = 0.2

[icPlayerPilot]
toggle_roll_yaw = 0
max_zoom_factor = 10
zoom_time = 0.5
max_rem_range = 50000

[icServerApp]
protocol = TCP/IP
host_name = "Templar's Lair"
cluster = badlands
system = ini:/multiplayer/maps/generic_02
package = dm
max_players = 16
time_limit = 600
score_limit = 10
tick_rate = 40
console_mode = 0

[icShip]
heat_gain_factor = 1
heat_loss_factor = 0.5
heat_damage_threshold = 500
heat_damage_rate = 0.08
critical_chance_scale = 12
critical_damage_scale = 0.2
criticals_per_impact = 0.2

[icSimTrackingMissile]
max_range_for_decoying_level_zero_missile = 500
min_range_for_stopping_level_one_missile_reacquisition = 5000

[icSolarSystem]
far_clip = 200000
preload_stations = 1

[icSPPlayerBaseScreen]
fritz_delay = 0.5
diorama_delay = 30
main_bay_url = lws:/avatars/base/setup
office_interior_url = lws:/avatars/base/setup_cal
jafs_url = lws:/avatars/base/setup_jafs
smith_url = lws:/avatars/base/setup_smith
gunbabes_url = lws:/avatars/base/setup_gb
normal_fog_colour = (0.25,0.35,0.2)
emergency_fog_colour = (0.23,0.05,0.05)
normal_fog_start = 400
emergency_fog_start = 100
normal_fog_end = 3000
emergency_fog_end = 1500
glow_channels[0] = floor01
glow_channels[1] = floor02
glow_channels[2] = floor03
glow_channels[3] = floor04
glow_channels[4] = roof1
glow_channels[5] = roof2side
glow_channels[6] = roof2mid
glow_channels[7] = snrvpit
normal_light_channel = baselights_normal
emergency_light_channel = baselights_emergency
lights_global = g_base_lights_on
dioramas_global = g_show_dioramas

[icStarfieldAvatar]
bright_star_count = 2000
dim_star_count = 100000
high_quality = 0
tint = (0.8,0.8,1)
seed = 314159276

[icTacticalCamera]
field_of_view = 1.2

[icTurretShip]
sensor_update_time = 1

[icTwoShotCamera]
field_of_view = 1.1

[icVisualEffects]
cull_detail = 0.005
low_detail = 0.04

[iiGun]
min_travel_time = 0.4
min_speed_fraction = 0.75
max_jitter_angle = 0.75
max_jitter_radius = 1.5

[iiShipSystem]
min_tri_weight = 0.5
max_tri_weight = 1.5

[iiSim]
mean_radius_of_reactor_explosion_sim = 200
collision_damage_sweet_speed = 600
collision_damage_factor = 3.5

[iiThrusterSim]
min_xy_lateral_acceleration_ratio = 0.2
min_xy_lateral_velocity_ratio = 0.2

;
; Other configuration data
;

[Debug]
dev_call_tracing = 0
dev_memory = 0
dev_package_assert = 0
dev_package_trace = 0
dev_string_statistics = 0
developer_mode = 0
log_file = flux.log
trace_level = 3
trace_to_console = 0
trace_to_debugger = 0
trace_to_log = 1

[Game]
GUIAvatarFactory = icWindowAvatarFactory
ShowLogo = 0


